-- Add AI-specific fields to menu_items table for AI-generated products
-- This script adds fields to support AI-generated products with enhanced metadata

-- Add AI-specific columns to menu_items table
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ai_prompt TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS nutritional_info JSONB;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ingredients TEXT[];
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS dietary_tags TEXT[];
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS difficulty_level VARCHAR DEFAULT 'medium';
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS spice_level VARCHAR DEFAULT 'medium';
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS cuisine_type VARCHAR;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS cooking_method VARCHAR;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS serving_size VARCHAR;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS prep_time INTEGER DEFAULT 15;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS cook_time INTEGER DEFAULT 20;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ai_confidence_score DECIMAL(3,2);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ai_generation_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ai_model_version VARCHAR;

-- Create index for AI-generated products
CREATE INDEX IF NOT EXISTS idx_menu_items_ai_generated ON menu_items(ai_generated);
CREATE INDEX IF NOT EXISTS idx_menu_items_difficulty_level ON menu_items(difficulty_level);
CREATE INDEX IF NOT EXISTS idx_menu_items_spice_level ON menu_items(spice_level);
CREATE INDEX IF NOT EXISTS idx_menu_items_cuisine_type ON menu_items(cuisine_type);

-- Create index for nutritional info (GIN index for JSONB)
CREATE INDEX IF NOT EXISTS idx_menu_items_nutritional_info ON menu_items USING GIN(nutritional_info);

-- Create index for ingredients array
CREATE INDEX IF NOT EXISTS idx_menu_items_ingredients ON menu_items USING GIN(ingredients);

-- Create index for dietary tags array
CREATE INDEX IF NOT EXISTS idx_menu_items_dietary_tags ON menu_items USING GIN(dietary_tags);

-- Add comments for documentation
COMMENT ON COLUMN menu_items.ai_generated IS 'Indicates if this product was generated by AI';
COMMENT ON COLUMN menu_items.ai_prompt IS 'The prompt used to generate this product';
COMMENT ON COLUMN menu_items.nutritional_info IS 'Nutritional information as JSON (calories, protein, carbs, fat, fiber)';
COMMENT ON COLUMN menu_items.ingredients IS 'Array of ingredients used in this product';
COMMENT ON COLUMN menu_items.dietary_tags IS 'Array of dietary tags (vegetarian, vegan, gluten-free, etc.)';
COMMENT ON COLUMN menu_items.difficulty_level IS 'Difficulty level: easy, medium, hard';
COMMENT ON COLUMN menu_items.spice_level IS 'Spice level: mild, medium, hot, extra_hot';
COMMENT ON COLUMN menu_items.cuisine_type IS 'Type of cuisine (italian, chinese, mexican, etc.)';
COMMENT ON COLUMN menu_items.cooking_method IS 'Method of cooking (grilled, fried, baked, etc.)';
COMMENT ON COLUMN menu_items.serving_size IS 'Serving size description';
COMMENT ON COLUMN menu_items.prep_time IS 'Preparation time in minutes';
COMMENT ON COLUMN menu_items.cook_time IS 'Cooking time in minutes';
COMMENT ON COLUMN menu_items.ai_confidence_score IS 'AI confidence score (0.00 to 1.00)';
COMMENT ON COLUMN menu_items.ai_generation_date IS 'When this product was generated by AI';
COMMENT ON COLUMN menu_items.ai_model_version IS 'Version of AI model used for generation';

-- Create a view for AI-generated products with enhanced information
CREATE OR REPLACE VIEW ai_products_view AS
SELECT 
    mi.id,
    mi.name,
    mi.description,
    mi.price,
    mi.image_url,
    mi.categories,
    mi.is_available,
    mi.is_featured,
    mi.preparation_time,
    mi.nutritional_info,
    mi.ingredients,
    mi.dietary_tags,
    mi.difficulty_level,
    mi.spice_level,
    mi.cuisine_type,
    mi.cooking_method,
    mi.serving_size,
    mi.prep_time,
    mi.cook_time,
    mi.ai_prompt,
    mi.ai_confidence_score,
    mi.ai_generation_date,
    mi.ai_model_version,
    mi.created_at,
    mi.updated_at,
    r.name as restaurant_name
FROM menu_items mi
LEFT JOIN restaurants r ON mi.restaurant_id = r.id
WHERE mi.ai_generated = true;

-- Create a function to get AI product statistics
CREATE OR REPLACE FUNCTION get_ai_product_stats()
RETURNS TABLE (
    total_ai_products BIGINT,
    avg_price DECIMAL(10,2),
    avg_prep_time DECIMAL(10,2),
    most_common_cuisine TEXT,
    most_common_difficulty TEXT,
    most_common_spice_level TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*) as total_ai_products,
        AVG(price) as avg_price,
        AVG(preparation_time) as avg_prep_time,
        MODE() WITHIN GROUP (ORDER BY cuisine_type) as most_common_cuisine,
        MODE() WITHIN GROUP (ORDER BY difficulty_level) as most_common_difficulty,
        MODE() WITHIN GROUP (ORDER BY spice_level) as most_common_spice_level
    FROM menu_items 
    WHERE ai_generated = true;
END;
$$ LANGUAGE plpgsql;

-- Create a function to search AI products by nutritional criteria
CREATE OR REPLACE FUNCTION search_ai_products_by_nutrition(
    max_calories INTEGER DEFAULT NULL,
    min_protein DECIMAL DEFAULT NULL,
    max_fat DECIMAL DEFAULT NULL,
    dietary_requirements TEXT[] DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    name VARCHAR,
    description TEXT,
    price DECIMAL(10,2),
    nutritional_info JSONB,
    dietary_tags TEXT[]
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        mi.id,
        mi.name,
        mi.description,
        mi.price,
        mi.nutritional_info,
        mi.dietary_tags
    FROM menu_items mi
    WHERE mi.ai_generated = true
    AND (max_calories IS NULL OR (mi.nutritional_info->>'calories')::INTEGER <= max_calories)
    AND (min_protein IS NULL OR (mi.nutritional_info->>'protein')::DECIMAL >= min_protein)
    AND (max_fat IS NULL OR (mi.nutritional_info->>'fat')::DECIMAL <= max_fat)
    AND (dietary_requirements IS NULL OR mi.dietary_tags && dietary_requirements);
END;
$$ LANGUAGE plpgsql;

-- Grant permissions for the view and functions
GRANT SELECT ON ai_products_view TO authenticated;
GRANT EXECUTE ON FUNCTION get_ai_product_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION search_ai_products_by_nutrition(INTEGER, DECIMAL, DECIMAL, TEXT[]) TO authenticated;
